import { useCallback, useRef } from 'react';
import { motion } from 'framer-motion';
import { Download, FileText, Share2, Copy, Check } from 'lucide-react';
import { useState } from 'react';
import type { AttackResult, Profile } from '../api';

/**
 * Report Export — Generate and download/share a security report
 * - Copy as plain text
 * - Download as HTML report
 * - Share via Web Share API
 */

interface ReportExportProps {
  profile: Profile;
  result: AttackResult;
}

function generateTextReport(profile: Profile, result: AttackResult): string {
  const lines = [
    '═══════════════════════════════════════',
    '  MIRRORTRAP — Security Exposure Report',
    '═══════════════════════════════════════',
    '',
    `Date: ${new Date().toLocaleString()}`,
    '',
    '── TARGET PROFILE ──',
    `Name: ${profile.name}`,
    `Role: ${profile.role}`,
    `Organization: ${profile.organization}`,
    `Recent Activity: ${profile.recentActivity}`,
    `Known Connection: ${profile.connection}`,
    '',
    '── EXPOSURE ASSESSMENT ──',
    `Score: ${result.exposure_score}/100`,
    `Verdict: ${result.overall_verdict}`,
    `Risk Level: ${result.exposure_score >= 70 ? 'HIGH' : result.exposure_score >= 40 ? 'MEDIUM' : 'LOW'}`,
    '',
    '── SIMULATED ATTACK ──',
    `Sender: ${result.sender_identity}`,
    `Channel: ${result.message_type}`,
    `Goal: ${result.attacker_goal}`,
    '',
    'Message:',
    result.attack_message,
    '',
    '── EXPLOITED VULNERABILITIES ──',
    ...( result.exploited_details?.map((d, i) =>
      `${i + 1}. [${d.trigger}] ${d.phrase}\n   Why: ${d.why_it_works}\n   Counter: ${d.counter}`
    ) || ['None detected']),
    '',
    '── RECOMMENDED ACTIONS ──',
    '1. Verify all unsolicited messages through official channels',
    '2. Never click links in unexpected messages',
    '3. Enable two-factor authentication',
    '4. Review and minimize your public digital footprint',
    '5. Report suspicious messages to your security team',
    '',
    '═══════════════════════════════════════',
    '  Generated by MirrorTrap',
    '  Educational use only — Not a real attack',
    '═══════════════════════════════════════',
  ];
  return lines.join('\n');
}

function generateHTMLReport(profile: Profile, result: AttackResult): string {
  const scoreColor = result.exposure_score >= 70 ? '#ef4444' : result.exposure_score >= 40 ? '#f59e0b' : '#22c55e';
  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>MirrorTrap Report — ${profile.name}</title>
<style>
  body{font-family:system-ui,sans-serif;background:#0b0b12;color:#e4e4e7;max-width:700px;margin:0 auto;padding:40px 24px}
  h1{color:#c084fc;font-size:28px;margin-bottom:4px}
  h2{color:#a1a1aa;font-size:14px;font-weight:400;margin-bottom:32px}
  h3{color:#f4f4f5;font-size:16px;border-bottom:1px solid rgba(255,255,255,0.1);padding-bottom:8px;margin-top:32px}
  .card{background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.06);border-radius:12px;padding:20px;margin:12px 0}
  .score{font-size:56px;font-weight:800;color:${scoreColor};text-align:center;margin:16px 0}
  .verdict{text-align:center;font-size:14px;color:${scoreColor};font-weight:600;margin-bottom:8px}
  .label{font-size:12px;color:#71717a;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:4px}
  .value{font-size:14px;color:#e4e4e7;margin-bottom:12px}
  .badge{display:inline-block;font-size:11px;font-weight:700;padding:2px 8px;border-radius:999px;margin:2px}
  .message{background:#1a2e1a;border:1px solid rgba(34,197,94,0.15);border-radius:12px;padding:16px;font-size:14px;line-height:1.7;white-space:pre-wrap;margin:12px 0}
  .vuln{background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.06);border-radius:8px;padding:14px;margin:8px 0}
  .footer{text-align:center;font-size:12px;color:#71717a;margin-top:40px;padding-top:20px;border-top:1px solid rgba(255,255,255,0.06)}
  @media print{body{background:white;color:#1a1a1a}.card,.vuln{border-color:#e5e7eb}.message{background:#f0fdf4;border-color:#bbf7d0}}
</style></head><body>
<h1>🛡️ MirrorTrap Report</h1>
<h2>Security Exposure Analysis — ${new Date().toLocaleDateString()}</h2>
<div class="card">
  <div class="label">Target Profile</div>
  <div class="value"><strong>${profile.name}</strong> · ${profile.role} at ${profile.organization}</div>
  <div class="label">Recent Activity</div>
  <div class="value">${profile.recentActivity}</div>
  <div class="label">Known Connection</div>
  <div class="value">${profile.connection}</div>
</div>
<div class="card">
  <div class="score">${result.exposure_score}<span style="font-size:20px;color:#71717a">/100</span></div>
  <div class="verdict">${result.overall_verdict}</div>
</div>
<h3>Simulated Attack</h3>
<div class="card">
  <div class="label">Impersonating</div>
  <div class="value">${result.sender_identity} via ${result.message_type}</div>
  <div class="label">Attacker Goal</div>
  <div class="value">${result.attacker_goal}</div>
</div>
<div class="message">${result.attack_message}</div>
<h3>Exploited Vulnerabilities</h3>
${(result.exploited_details || []).map(d => `
<div class="vuln">
  <span class="badge" style="background:rgba(168,85,247,0.1);color:#c084fc;border:1px solid rgba(168,85,247,0.3)">${d.trigger}</span>
  <div style="margin-top:8px;font-size:13px"><strong>Phrase:</strong> "${d.phrase}"</div>
  <div style="margin-top:4px;font-size:13px"><strong>Why it works:</strong> ${d.why_it_works}</div>
  <div style="margin-top:4px;font-size:13px;color:#86efac"><strong>Counter:</strong> ${d.counter}</div>
</div>`).join('')}
<h3>Recommended Actions</h3>
<div class="card">
  <ol style="padding-left:20px;line-height:2;font-size:14px">
    <li>Verify <strong>${result.sender_identity}</strong> through official channels</li>
    <li>Never click links in unsolicited messages</li>
    <li>Enable two-factor authentication on all accounts</li>
    <li>Review and minimize your public digital footprint</li>
    <li>Report suspicious messages to your security team</li>
  </ol>
</div>
<div class="footer">
  Generated by MirrorTrap — Educational social engineering exposure engine<br>
  This is a simulated attack for awareness purposes only.
</div>
</body></html>`;
}

export default function ReportExport({ profile, result }: ReportExportProps) {
  const [copied, setCopied] = useState(false);
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const handleCopy = useCallback(() => {
    const text = generateTextReport(profile, result);
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
      timeoutRef.current = setTimeout(() => setCopied(false), 2000);
    });
  }, [profile, result]);

  const handleDownload = useCallback(() => {
    const html = generateHTMLReport(profile, result);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mirrortrap-report-${profile.name.toLowerCase().replace(/\s/g, '-')}-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }, [profile, result]);

  const handleShare = useCallback(async () => {
    if (navigator.share) {
      const text = generateTextReport(profile, result);
      try {
        await navigator.share({
          title: `MirrorTrap Report — ${profile.name}`,
          text: text.slice(0, 500) + '...',
        });
      } catch { /* user cancelled */ }
    }
  }, [profile, result]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.8, duration: 0.5 }}
      className="glass-card"
      style={{ padding: 20, marginTop: 24 }}
    >
      <div style={{
        fontSize: 11, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase',
        color: 'var(--text-muted)', marginBottom: 14, display: 'flex', alignItems: 'center', gap: 8,
      }}>
        <FileText size={14} style={{ color: 'var(--accent-purple)' }} />
        Export Report
      </div>

      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
        <ExportBtn onClick={handleDownload} icon={<Download size={14} />} label="Download HTML" color="#60a5fa" />
        <ExportBtn onClick={handleCopy} icon={copied ? <Check size={14} /> : <Copy size={14} />} label={copied ? 'Copied!' : 'Copy Text'} color={copied ? '#22c55e' : '#a78bfa'} />
        {typeof navigator !== 'undefined' && 'share' in navigator && (
          <ExportBtn onClick={handleShare} icon={<Share2 size={14} />} label="Share" color="#f59e0b" />
        )}
      </div>
    </motion.div>
  );
}

function ExportBtn({ onClick, icon, label, color }: { onClick: () => void; icon: React.ReactNode; label: string; color: string }) {
  return (
    <button
      onClick={onClick}
      style={{
        display: 'flex', alignItems: 'center', gap: 6,
        padding: '8px 16px', fontSize: 12, fontWeight: 600,
        color, background: `${color}08`, border: `1px solid ${color}20`,
        borderRadius: 8, cursor: 'pointer', fontFamily: 'var(--font-sans)',
        transition: 'all 0.2s',
      }}
      onMouseEnter={(e) => { e.currentTarget.style.background = `${color}15`; e.currentTarget.style.borderColor = `${color}40`; }}
      onMouseLeave={(e) => { e.currentTarget.style.background = `${color}08`; e.currentTarget.style.borderColor = `${color}20`; }}
    >
      {icon} {label}
    </button>
  );
}
